config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, :controllers => { registrations: 'registrations' }
  mount RedactorRails::Engine => '/redactor_rails'
  resources :users
  resources :posts do 
  resources :comments
  end
root 'posts#index'
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :posts
	has_and_belongs_to_many :categories
end

app/models/comment.rb
class Comment < ActiveRecord::Base
has_ancestry
belongs_to :commentable, :polymorphic => true
end

app/models/post.rb
class Post < ActiveRecord::Base
has_many :comments, :as => :commentable, :dependent => :destroy
has_and_belongs_to_many :categories
validates :title, presence: true, length: { minimum: 5 }

end

app/models/redactor_rails/asset.rb
class RedactorRails::Asset < ActiveRecord::Base
  include RedactorRails::Orm::ActiveRecord::AssetBase
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  validates_presence_of :data
end

app/models/redactor_rails/document.rb
class RedactorRails::Document < RedactorRails::Asset
  mount_uploader :data, RedactorRailsDocumentUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end

  def as_json_methods
    [:image]
  end
end

app/models/redactor_rails/picture.rb
class RedactorRails::Picture < RedactorRails::Asset
  mount_uploader :data, RedactorRailsPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_and_belongs_to_many :categories
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         after_create :welcome_message
  private
  def welcome_message
   UserMailer.welcome_email(self).deliver
  end
#private

 # def welcome_message
  #  UserMailer.welcome_email(self).deliver
  #end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,:except =>[:index,:show]
   protect_from_forgery with: :exception
    before_action :set_categories

   
private
    def set_categories
        @categories = Category.all
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
def new
    @parent_id = params.delete(:parent_id)
    @commentable = find_commentable
    @comment = Comment.new( :parent_id => @parent_id, 
                            :commentable_id => @commentable.id,
                            :commentable_type => @commentable.class.to_s)
  end
  
  def create
    @commentable = find_commentable
    @comment = @commentable.comments.build(comment_params)
    if @comment.save
      flash[:notice] = "Successfully created comment."
      redirect_to @commentable
    else
      flash[:error] = "Error adding comment."
    end
  end
 
  private
      def comment_params
      params.require(:comment).permit(:commenter,:body,:parent_id, :commentable_id, :commentable_type)
    end
     def find_commentable
       params.each do |name, value|
          if name =~ /(.+)_id$/
           return $1.classify.constantize.find(value)
          end
       end
       nil
      end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  include Com::Commentable
  # GET /posts
  # GET /posts.json
  def index
  if params[:format]
      @posts = Category.find(params[:format]).posts.order('created_at DESC').paginate(:page => params[:page],:per_page => 4)
    else
      @posts = Post.order('created_at DESC').paginate(:page => params[:page],:per_page => 4)
    end
    @categories = Category.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :body,{ category_ids:[] })
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
private
def sign_up_params
params.require(:user).permit( :email, :password, :password_confirmation )
end
def account_update_params
params.require(:user).permit( :email, :password, :password_confirmation, :current_password,{category_ids:[]})
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_filter :authenticate_user!

  def index
    @users = current_user
  end
  def update 
  	@user = current_user.id
  	params[:product][:category_ids] ||= []
  	if @user.update(user_params)
  		flash[:success] = "Profile updated."
  		redirect_to @user
  	else 
  		render 'edit'
  	end
  end 
  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Access denied."
    end
  end

private
def sign_up_params
params.require(:user).permit( :email, :password, :password_confirmation )
end
def account_update_params
params.require(:user).permit( :email, :password, :password_confirmation, :current_password,{category_ids:[]})
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
def nested_comments(comments)
    comments.map do |comment, sub_comments|
      content_tag(:div, render(comment), :class => "col-md-offset-1
")
    end.join.html_safe
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.haml
.commentdiv
  %h5.family 
    %strong 
      = comment.commenter 
    %small
      = comment.created_at.strftime('%b %d, %Y at %H:%M') 
  %p.family=  comment.body
  .actions
    -if comment.depth <6
      = link_to "Reply", new_polymorphic_path([@commentable, Comment.new], :parent_id => comment),:class=>"btn btn-default btn-xs family"
= nested_comments comment.children

app/views/comments/_form.html.haml
= bootstrap_form_for [@commentable, @comment] do |f|
  = f.hidden_field :parent_id
  %p.family
    = f.label :New_comment
    %br
  %p.family
   
    = f.text_field :commenter
   
  %p.family
    = f.text_area :body, :rows => 4
  %p.family
    = f.submit "Post Comment"

app/views/comments/new.html.erb
<%= render 'form'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>App</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Annie+Use Your Telescope' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<div  class="container w hed">
<nav class="navbar navbar-default w">
<ul class="nav navbar-nav ">
<p class="navbar-brand family fff ">News Portal</p>

 <li class="family ff"><%= link_to "All Posts",posts_path %> </li>
<% @categories.each do |c| %>
<li class="family ff">  <%= link_to c.name, posts_path(c) %></li>
<% end %>
</ul>
<% if user_signed_in? %>
   <%= link_to 'Sing Out', destroy_user_session_path, method: 'delete',:class=>"btn btn-default pos family fff" %> 
  <% else %>
   <%= link_to 'Sing In', new_user_session_path, method: 'post',:class=>"btn btn-primary pos family fff"  %>
  <% end %>
  <%if user_signed_in?%>
   <%= link_to 'Go Admin','admin#login',:class=>"btn btn-primary pos family fff" %>
  <%end%>
</nav>
</div>
<div class="container w">
        <div id="sidebar" class="col-xs-2">
          <!-- sidebar content -->
       <%if user_signed_in? %>
<%= link_to 'New Post', new_post_path,:class=>'btn btn-primary family fs poss' %>
   </br>
   <%= link_to 'Profile', users_path,:class =>"btn btn-primary family fs poss" %>
   </br>
   
   <%= link_to 'Edit account', edit_user_registration_path,:class=>"btn btn-warning family fs poss" %>
   <%else%>
   <%=image_tag("me.jpg",:class =>'img-circle poss',size: "120x120")%>
   <p class="f family">
      Developed by:</br>
     Somar Melhem </br>
     jonior developer</br> 
     Ruby on Rails 

   </p>
   <%end%>
   </div>
   <div id="content" class="col-xs-9">
          <!--  main content -->
   

<%= yield %>
     </div>
</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= bootstrap_form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class ="field">
  <%= collection_check_boxes(:post, :category_ids, Category.all, :id, :name)%>
</div>
  <div class="field">
    
    <%= f.text_field :title %>
  </div>
  <div class="field">
   
    <%= f.text_area :description %>
  </div>
  <div class="field">
    
    <%= f.text_area :body,:class => "redactor", :rows => 10, :cols => 15 %>
  </div>

  <div class="actions">
    <%= f.submit :class=>"btn btn-primary family fs"%>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

    <% @posts.each do |post| %>
     <div class="postdiv">
        <h3 ><%= link_to post.title ,post,:class=>"btn-link family fff"%><br/>
        <small class="family fs" ><%= post.description %></small></h3>
         <footer class="ss family">Created <%= time_ago_in_words(post.created_at) %> ago</footer>
         <footer class="ss family">Comments <%= post.comments.count%></footer>   
      <!--  <%= link_to 'Edit', edit_post_path(post),:class=>"btn btn-default btn-xs"  %> 
        <%= link_to 'Destroy', post,:class=>"btn btn-default btn-xs" , method: :delete, data: { confirm: 'Are you sure?' } %>
        -->
        
       </div>
    <% end %>
 
<br>
<%= will_paginate @posts, renderer: BootstrapPagination::Rails ,:class=>"pagin" %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>
</br>
<%= link_to 'Back', posts_path ,:class =>"btn btn-default family fs"%>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="postdiv" style="padding-bottom:10px;">
<h3 class="family"><strong>  <%= @post.title %> </strong> 
<small class="ss" >Posted: <%= time_ago_in_words(@post.created_at) %> ago</small>
</h3>

 <h5 style="padding-bottom:10px;" class="family"> <%= @post.description %></h5>

<p class="family">
  <%= @post.body.html_safe %>
</p>
<!--
<%= link_to 'Edit', edit_post_path(@post) %> |-->
<%= link_to 'Back', posts_path ,:class=>"btn btn-default family"%>
</div>
<h4 class="family">Comments :</h4>
<%= nested_comments @comments%>
<%= render "comments/form"%>

app/views/users/_user.html.erb
<td><%= link_to user.name, user %></td>
<td><%= link_to user.email, user %></td>

app/views/users/index.html.erb
<h3>Profile</h3>
<strong>On this E-Mail " <%= current_user.email%> "  you will get info about all news that will be added to this site ;) </strong>

<p>Till now you applied on this Categories of post to get informed about :</p>
<ul>
<% current_user.categories.each do |cat|%>
<li><%= cat.name%></li>
<%end%>
</ul>
<i>you can change them in Edit account</i>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>